create table hibernate_sequence (next_val bigint) engine=InnoDB;
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
insert into hibernate_sequence values ( 1 );
create table t_cooking_method (id bigint not null, primary key (id)) engine=InnoDB;
create table t_food_product (id bigint not null, carbohydrates decimal(19,2), fat decimal(19,2), kilocalories decimal(19,2), proteins decimal(19,2), primary key (id)) engine=InnoDB;
create table t_localization (id bigint not null, entity_type integer not null, locale varchar(2) not null, value longtext not null, entity_id bigint not null, primary key (id)) engine=InnoDB;
create table t_measure (id bigint not null, primary key (id)) engine=InnoDB;
create table t_recipe (id bigint not null, cooking_time integer not null, date_of_creation datetime not null, is_approved bit not null, prep_time integer not null, user_id bigint not null, primary_cooking_method bigint not null, primary key (id)) engine=InnoDB;
create table t_recipe_description (id bigint not null, recipe_id bigint not null, primary key (id)) engine=InnoDB;
create table t_recipe_ingredient (id bigint not null, amount double precision, is_optional bit, food_product_id bigint not null, measure_id bigint not null, recipe_id bigint not null, primary key (id)) engine=InnoDB;
create table t_recipe_secondary_cooking_method (recipe_id bigint not null, cooking_method_id bigint not null, primary key (recipe_id, cooking_method_id)) engine=InnoDB;
create table t_recipe_step (id bigint not null, step_index integer not null, recipe_id bigint not null, primary key (id)) engine=InnoDB;
create table t_role (id bigint not null, name varchar(50) not null, primary key (id)) engine=InnoDB;
create table t_user (id bigint not null, avatar_url varchar(255) default '/img/user/avatar.jpg' not null, date_of_creation datetime not null, email varchar(50) not null, first_name varchar(50), is_email_confirmed bit not null, last_name varchar(50), password varchar(100) not null, username varchar(30) not null, primary key (id)) engine=InnoDB;
create table t_user_role (user_id bigint not null, role_id bigint not null, primary key (user_id, role_id)) engine=InnoDB;
alter table t_localization add constraint uk_localization_loc_ent_id unique (locale, entity_id);
alter table t_role add constraint uk_role_name unique (name);
alter table t_user add constraint uk_user_username unique (username);
alter table t_user add constraint uk_user_email unique (email);
alter table t_recipe add constraint fk_recipe_user_id foreign key (user_id) references t_user (id);
alter table t_recipe add constraint fk_recipe_cooking_method_id foreign key (primary_cooking_method) references t_cooking_method (id);
alter table t_recipe_description add constraint fk_recipe_description_recipe_id foreign key (recipe_id) references t_recipe (id);
alter table t_recipe_ingredient add constraint fk_recipe_ingredient_food_id foreign key (food_product_id) references t_food_product (id);
alter table t_recipe_ingredient add constraint fk_recipe_ingredient_measure_id foreign key (measure_id) references t_measure (id);
alter table t_recipe_ingredient add constraint fk_recipe_ingredient_recipe_id foreign key (recipe_id) references t_recipe (id);
alter table t_recipe_secondary_cooking_method add constraint fk_recipe_cooking_method_cm_id foreign key (cooking_method_id) references t_cooking_method (id);
alter table t_recipe_secondary_cooking_method add constraint fk_recipe_cooking_method_rec_id foreign key (recipe_id) references t_recipe (id);
alter table t_recipe_step add constraint fk_recipe_step_recipe_id foreign key (recipe_id) references t_recipe (id);
alter table t_user_role add constraint fk_user_role_role_id foreign key (role_id) references t_role (id);
alter table t_user_role add constraint fk_user_role_user_id foreign key (user_id) references t_user (id);